name: Deploy to VPS

on:
  push:
    branches:
      - main
      - deploy-project-to-vps
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/sheet-to-tiktok-automation
            git pull origin main
            docker-compose down
            docker-compose up -d
            docker-compose logs -f automation
